# Uncomment this line to define a global platform for your project
platform :ios, "7.1"

target "TwitLocation" do

pod 'ReactiveCocoa', '2.3.1'
pod 'Nimbus', '1.2.0'

end

target "TwitLocationTests" do

end

